const templates = {
  A1001: {
    name: "页面展示",
    price: 18,
    pages: 5,
    desc: "适用于企业形象展示，包含公司简介、产品服务和联系我们页面。",

    images: [
      "images/demo1 (2).jpeg",
      "images/demo1 (3).jpeg",
      "images/demo1 (4).jpeg",
      "images/demo1 (5).jpeg",
      "images/demo1 (6).jpeg",
    ],
    galleryText:
      "说明：成品源码属于可多次销售的哦，但是同一个学校同一份只卖一次，所以请一定要备注学校全称，避免重复！请理解哦！ 成品不提供技术指导和免费修改服务的哈，不支持退换货的哦，拍前请选好自己心仪的网页成品！",
  },
  A1002: {
    name: "页面展示",
    price: 20,
    pages: 7,
    desc: "适合餐饮和美食推荐类网站，支持菜品分类与相册。",
    mainImage: "images/demo2(6).jpeg",
    images: [
      "images/demo2 (6).jpeg",
      "images/demo2 (2).jpeg",
      "images/demo2 (3).jpeg",
      "images/demo2 (4).jpeg",
      "images/demo2 (5).jpeg",
    ],
  },
  A1003: {
    name: "页面展示",
    price: 25,
    pages: 7,
    desc: "页面结构轮播图，视频",
    mainImage: "images/demo3(6).jpeg",
    images: [
      "images/demo3(6).jpeg",
      "images/demo3 (2).jpeg",
      "images/demo3 (3).jpeg",
      "images/demo3 (4).jpeg",
      "images/demo3 (5).jpeg",
    ],
  },
  A1004: {
    name: "页面展示",
    price: 20,
    pages: 7,
    desc: "电商购物网站模板，含商品列表、购物车与订单页面。",
    mainImage: "images/demo4 (2).jpeg",
    images: [
      "images/demo4 (2).jpeg",
      "images/demo4 (3).jpeg",
      "images/demo4 (4).jpeg",
      "images/demo4 (6).jpeg",
      "images/demo4 (5).jpeg",
    ],
  },
  A1005: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "旅游网站模板，展示路线、景点与行程。",
    mainImage: "images/demo5 (6).jpeg",
    images: [
      "images/demo5 (2).jpeg",
      "images/demo5 (3).jpeg",
      "images/demo5 (4).jpeg",
      "images/demo5 (5).jpeg",
    ],
  },
  A1006: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",

    images: [
      "images/demo6 (1).jpeg",
      "images/demo6 (2).jpeg",
      "images/demo6 (3).jpeg",
      "images/demo6 (4).jpeg",
      "images/demo6 (5).jpeg",
    ],
  },
  A1007: {
    name: "页面展示",
    price: 20,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo7 (2).jpeg",
      "images/demo7 (3).jpeg",
      "images/demo7 (4).jpeg",
      "images/demo7 (5).jpeg",
      "images/demo7 (6).jpeg",
    ],
  },
  A1008: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo8 (2).jpeg",
      "images/demo8 (3).jpeg",
      "images/demo8 (4).jpeg",
      "images/demo8 (5).jpeg",
      "images/demo8 (6).jpeg",
    ],
  },
  A1009: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo9 (2).jpeg",
      "images/demo9 (3).jpeg",
      "images/demo9 (4).jpeg",
      "images/demo9 (5).jpeg",
      "images/demo9 (6).jpeg",
    ],
  },
  A10010: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo10 (2).jpeg",
      "images/demo10 (3).jpeg",
      "images/demo10 (4).jpeg",
      "images/demo10 (5).jpeg",
      "images/demo10 (6).jpeg",
    ],
  },
  A10011: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo11 (2).jpeg",
      "images/demo11 (3).jpeg",
      "images/demo11 (4).jpeg",
      "images/demo11 (5).jpeg",
      "images/demo11 (6).jpeg",
    ],
  },
  A10012: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo12 (2).jpeg",
      "images/demo12 (3).jpeg",
      "images/demo12 (4).jpeg",
      "images/demo12 (5).jpeg",
      "images/demo12 (6).jpeg",
    ],
  },
  A10013: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo13 (2).jpeg",
      "images/demo13 (3).jpeg",
      "images/demo13 (4).jpeg",
      "images/demo13 (5).jpeg",
      "images/demo13 (6).jpeg",
    ],
  },
  A10014: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo14 (1).jpeg",
      "images/demo14 (3).jpeg",
      "images/demo14 (4).jpeg",
      "images/demo14 (5).jpeg",
      "images/demo14 (6).jpeg",
    ],
  },
  A10015: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo15 (2).jpeg",
      "images/demo15 (3).jpeg",
      "images/demo15 (4).jpeg",
      "images/demo15 (5).jpeg",
      "images/demo15 (6).jpeg",
    ],
  },
  A10016: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo16 (2).jpeg",
      "images/demo16 (3).jpeg",
      "images/demo16 (4).jpeg",
      "images/demo16 (5).jpeg",
      "images/demo16 (6).jpeg",
    ],
  },
  A10017: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo17 (2).jpeg",
      "images/demo17 (3).jpeg",
      "images/demo17 (4).jpeg",
      "images/demo17 (5).jpeg",
      "images/demo17 (6).jpeg",
    ],
  },
  A10018: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo18 (2).jpeg",
      "images/demo18 (3).jpeg",
      "images/demo18 (4).jpeg",
      "images/demo18 (5).jpeg",
      "images/demo18 (6).jpeg",
    ],
  },
  A10019: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo19 (2).jpeg",
      "images/demo19 (3).jpeg",
      "images/demo19 (4).jpeg",
      "images/demo19 (5).jpeg",
      "images/demo19 (6).jpeg",
    ],
  },
  A10020: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo20 (2).jpeg",
      "images/demo20 (3).jpeg",
      "images/demo20 (4).jpeg",
      "images/demo20 (5).jpeg",
      "images/demo20 (6).jpeg",
    ],
  },
  A10021: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo21 (2).jpeg",
      "images/demo21 (3).jpeg",
      "images/demo21 (4).jpeg",
      "images/demo21 (5).jpeg",
      "images/demo21 (6).jpeg",
    ],
  },
  A10022: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo22 (2).jpeg",
      "images/demo22 (3).jpeg",
      "images/demo22 (4).jpeg",
      "images/demo22 (5).jpeg",
      "images/demo22 (6).jpeg",
    ],
  },
  A10023: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo23 (2).jpeg",
      "images/demo23 (3).jpeg",
      "images/demo23 (4).jpeg",
      "images/demo23 (5).jpeg",
      "images/demo23 (6).jpeg",
    ],
  },
  A10024: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo24 (2).jpeg",
      "images/demo24 (3).jpeg",
      "images/demo24 (4).jpeg",
      "images/demo24 (5).jpeg",
      "images/demo24 (6).jpeg",
    ],
  },
  A10025: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo25 (2).jpeg",
      "images/demo25 (3).jpeg",
      "images/demo25 (4).jpeg",
      "images/demo25 (5).jpeg",
      "images/demo25 (6).jpeg",
    ],
  },
  A10026: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo26 (2).jpeg",
      "images/demo26 (3).jpeg",
      "images/demo26 (4).jpeg",
      "images/demo26 (5).jpeg",
      "images/demo26 (6).jpeg",
    ],
  },
  A10027: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo27 (2).jpeg",
      "images/demo27 (3).jpeg",
      "images/demo27 (4).jpeg",
      "images/demo27 (5).jpeg",
      "images/demo27 (6).jpeg",
    ],
  },
  A10028: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo28 (2).jpeg",
      "images/demo28 (3).jpeg",
      "images/demo28 (4).jpeg",
      "images/demo28 (5).jpeg",
      "images/demo28 (6).jpeg",
    ],
  },
  A10029: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo29 (2).jpeg",
      "images/demo29 (3).jpeg",
      "images/demo29 (4).jpeg",
      "images/demo29 (5).jpeg",
      "images/demo29 (6).jpeg",
    ],
  },
  A10030: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo30 (2).jpeg",
      "images/demo30 (3).jpeg",
      "images/demo30 (4).jpeg",
      "images/demo30 (5).jpeg",
      "images/demo30 (6).jpeg",
    ],
  },
  A10031: {
    name: "页面展示",
    price: 15,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo31 (2).jpeg",
      "images/demo31 (3).jpeg",
      "images/demo31 (4).jpeg",
      "images/demo31 (5).jpeg",
      "images/demo31 (6).jpeg",
    ],
  },
  A10032: {
    name: "页面展示",
    price: 18,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo32 (2).jpeg",
      "images/demo32 (3).jpeg",
      "images/demo32 (4).jpeg",
      "images/demo32 (5).jpeg",
      "images/demo32 (6).jpeg",
    ],
  },
  A10033: {
    name: "页面展示",
    price: 15,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo33 (2).jpeg",
      "images/demo33 (3).jpeg",
      "images/demo33 (4).jpeg",
      "images/demo33 (5).jpeg",
      "images/demo33 (6).jpeg",
    ],
  },
  A10034: {
    name: "页面展示",
    price: 18,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo34 (2).jpeg",
      "images/demo34 (3).jpeg",
      "images/demo34 (4).jpeg",
      "images/demo34 (5).jpeg",
      "images/demo34 (6).jpeg",
    ],
  },
  A10035: {
    name: "页面展示",
    price: 12,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo35 (2).jpeg",
      "images/demo35 (3).jpeg",
      "images/demo35 (4).jpeg",
      "images/demo35 (5).jpeg",
      "images/demo35 (6).jpeg",
    ],
  },
  A10036: {
    name: "页面展示",
    price: 12,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo36 (2).jpeg",
      "images/demo36 (3).jpeg",
      "images/demo36 (4).jpeg",
      "images/demo36 (5).jpeg",
      "images/demo36 (6).jpeg",
    ],
  },
  A10037: {
    name: "页面展示",
    price: 12,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo37 (2).jpeg",
      "images/demo37 (3).jpeg",
      "images/demo37 (4).jpeg",
      "images/demo37 (5).jpeg",
      "images/demo37 (6).jpeg",
    ],
  },
  A10038: {
    name: "页面展示",
    price: 12,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo38 (2).jpeg",
      "images/demo38 (3).jpeg",
      "images/demo38 (4).jpeg",
      "images/demo38 (5).jpeg",
      "images/demo38 (6).jpeg",
    ],
  },
  A10039: {
    name: "页面展示",
    price: 10,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo39 (2).jpeg",
      "images/demo39 (3).jpeg",
      "images/demo39 (4).jpeg",
      "images/demo39 (5).jpeg",
      "images/demo39 (6).jpeg",
    ],
  },
  A10040: {
    name: "页面展示",
    price: 10,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo40 (2).jpeg",
      "images/demo40 (3).jpeg",
      "images/demo40 (4).jpeg",
      "images/demo40 (5).jpeg",
      "images/demo40 (6).jpeg",
    ],
  },
  A10041: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo41 (2).jpeg",
      "images/demo41 (3).jpeg",
      "images/demo41 (4).jpeg",
      "images/demo41 (5).jpeg",
      "images/demo41 (6).jpeg",
    ],
  },
  A10042: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo42 (2).jpeg",
      "images/demo42 (3).jpeg",
      "images/demo42 (4).jpeg",
      "images/demo42 (5).jpeg",
      "images/demo42 (6).jpeg",
    ],
  },
  A10043: {
    name: "页面展示",
    price: 20,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo43 (2).jpeg",
      "images/demo43 (3).jpeg",
      "images/demo43 (4).jpeg",
      "images/demo43 (5).jpeg",
    ],
  },
  A10044: {
    name: "页面展示",
    price: 20,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo44 (2).jpeg",
      "images/demo44 (3).jpeg",
      "images/demo44 (4).jpeg",
      "images/demo44 (5).jpeg",
      "images/demo44 (6).jpeg",
    ],
  },
  A10045: {
    name: "页面展示",
    price: 20,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo45 (2).jpeg",
      "images/demo45 (3).jpeg",
      "images/demo45 (4).jpeg",
      "images/demo45 (5).jpeg",
      "images/demo45 (6).jpeg",
    ],
  },
  A10046: {
    name: "页面展示",
    price: 18,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo46 (2).jpeg",
      "images/demo46 (3).jpeg",
      "images/demo46 (4).jpeg",
      "images/demo46 (5).jpeg",
      "images/demo46 (6).jpeg",
    ],
  },
  A10047: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo47 (2).jpeg",
      "images/demo47 (3).jpeg",
      "images/demo47 (4).jpeg",
      "images/demo47 (5).jpeg",
      "images/demo47 (6).jpeg",
    ],
  },
  A10048: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo48 (2).jpeg",
      "images/demo48 (3).jpeg",
      "images/demo48 (4).jpeg",
      "images/demo48 (5).jpeg",
      "images/demo48 (6).jpeg",
    ],
  },
  A10049: {
    name: "页面展示",
    price: 16,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo49 (2).jpeg",
      "images/demo49 (3).jpeg",
      "images/demo49 (4).jpeg",
      "images/demo49 (5).jpeg",
      "images/demo49 (6).jpeg",
    ],
  },
  A10050: {
    name: "页面展示",
    price: 18,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo50 (2).jpeg",
      "images/demo50 (3).jpeg",
      "images/demo50 (4).jpeg",
      "images/demo50 (5).jpeg",
      "images/demo50 (6).jpeg",
    ],
  },
  A10051: {
    name: "页面展示",
    price: 18,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo51 (2).jpeg",
      "images/demo51 (3).jpeg",
      "images/demo51 (4).jpeg",
      "images/demo51 (5).jpeg",
      "images/demo51 (6).jpeg",
    ],
  },
  A10052: {
    name: "页面展示",
    price: 15,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo52 (2).jpeg",
      "images/demo52 (3).jpeg",
      "images/demo52 (4).jpeg",
      "images/demo52 (5).jpeg",
      "images/demo52 (6).jpeg",
    ],
  },
  A10053: {
    name: "页面展示",
    price: 15,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo53 (2).jpeg",
      "images/demo53 (3).jpeg",
      "images/demo53 (4).jpeg",
      "images/demo53 (5).jpeg",
      "images/demo53 (6).jpeg",
    ],
  },
  A10054: {
    name: "页面展示",
    price: 10,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo54 (2).jpeg",
      "images/demo54 (3).jpeg",
      "images/demo54 (4).jpeg",
      "images/demo54 (5).jpeg",
      "images/demo54 (6).jpeg",
    ],
  },
  A10055: {
    name: "页面展示",
    price: 15,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo55 (2).jpeg",
      "images/demo55 (3).jpeg",
      "images/demo55 (4).jpeg",
      "images/demo55 (5).jpeg",
      "images/demo55 (6).jpeg",
    ],
  },
  A10056: {
    name: "页面展示",
    price: 18,
    pages: 7,
    desc: "适用于教育机构、课程介绍与报名展示。",
    images: [
      "images/demo56 (2).jpeg",
      "images/demo56 (3).jpeg",
      "images/demo56 (4).jpeg",
      "images/demo56 (5).jpeg",
      "images/demo56 (6).jpeg",
    ],
  },
};
